---
# Source: plausible-analytics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-plausible-analytics
  labels:
    helm.sh/chart: plausible-analytics-0.2.5
    app.kubernetes.io/name: plausible-analytics
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.3.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: plausible-analytics/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-plausible-analytics
  labels:
    app: plausible
    helm.sh/chart: plausible-analytics-0.2.5
    app.kubernetes.io/name: plausible-analytics
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.3.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQDAuMC4wLjA6NTQzMi9wbGF1c2libGU=
  CLICKHOUSE_DATABASE_URL: aHR0cDovL3BsYXVzaWJsZS1jbGlja2hvdXNlOjgxMjMvcGxhdXNpYmxlX2V2ZW50c19kYg==
  SECRET_KEY_BASE: ZE5xM1pCcW5XcE45Mk1PN2x4UWFLd25LNk5yeEdQVmRXNG1vcHdPRDBwTm1ESlgxb2VmMGNldHhYVDZLSXh0a0Rqa2lqNENycUh1QkNYNXBnYm5hWFI4dVdS
---
# Source: plausible-analytics/charts/clickhouseServer/templates/configmap-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-clickhouseServer-config
  labels:
    app.kubernetes.io/name: clickhouseServer-config
    app.kubernetes.io/instance: release-name-config
    app.kubernetes.io/managed-by: Helm
data:
  config.xml: |-
    <?xml version="1.0"?>
    <yandex>
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
        
        <include_from>/etc/clickhouse-server/metrica.d/metrica.xml</include_from>

        <users_config>users.xml</users_config>
        
        <display_name>release-name-clickhouseServer</display_name>
        <listen_host>0.0.0.0</listen_host>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <interserver_http_port>9009</interserver_http_port>
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        <timezone>Europe/Paris</timezone>
        <umask>022</umask>
        <mlock_executable>false</mlock_executable>
        <remote_servers incl="clickhouse_remote_servers" optional="true" />
        <zookeeper incl="zookeeper-servers" optional="true" />
        <macros incl="macros" optional="true" />
        <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
        <max_session_timeout>3600</max_session_timeout>
        <default_session_timeout>60</default_session_timeout>
        <disable_internal_dns_cache>1</disable_internal_dns_cache>

        <query_log>
            <database>system</database>
            <table>query_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_log>

        <query_thread_log>
            <database>system</database>
            <table>query_thread_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_thread_log>

        <distributed_ddl>
            <path>/clickhouse/task_queue/ddl</path>
        </distributed_ddl>
        <logger>
            <level>trace</level>
            <log>/var/log/clickhouse-server/clickhouse-server.log</log>
            <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
            <size>1000M</size>
            <count>10</count>
        </logger>
    </yandex>
---
# Source: plausible-analytics/charts/clickhouseServer/templates/configmap-metrika.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-clickhouseServer-metrica
  labels:
    app.kubernetes.io/name: clickhouseServer-metrica
    app.kubernetes.io/instance: release-name-metrica
    app.kubernetes.io/managed-by: Helm
data:
  metrica.xml: |-
    <?xml version="1.0"?>
    <yandex>
        <clickhouse_remote_servers>
            <release-name-clickhouseServer>
                <shard>
                    <replica>
                        <internal_replication>false</internal_replication>
                        <host>release-name-clickhouseServer-0.release-name-clickhouseServer-headless.invoiceninja.svc.cluster.local</host>
                        <port>9000</port>
                        <user>default</user>
                        <compression>true</compression>
                    </replica>
                </shard>
            </release-name-clickhouseServer>
        </clickhouse_remote_servers>
    </yandex>
---
# Source: plausible-analytics/charts/clickhouseServer/templates/configmap-users.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-clickhouseServer-users
  labels:
    app.kubernetes.io/name: clickhouseServer-users
    app.kubernetes.io/instance: release-name-users
    app.kubernetes.io/managed-by: Helm
data:
  users.xml: |-
    <?xml version="1.0"?>
    <yandex>
    </yandex>
---
# Source: plausible-analytics/charts/clickhouseServer/templates/svc-clickhouse-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-clickhouseServer-headless
  labels:
    app.kubernetes.io/name: clickhouseServer-headless
    app.kubernetes.io/instance: release-name-headless
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: "None"
  ports:
  - port: 9000
    targetPort: tcp-port
    protocol: TCP
    name: tcp-port
  - port: 8123
    targetPort: http-port
    protocol: TCP
    name: http-port
  - port: 9009
    targetPort: inter-http-port
    protocol: TCP
    name: inter-http-port
  selector:
    app.kubernetes.io/name: clickhouseServer
    app.kubernetes.io/instance: release-name
---
# Source: plausible-analytics/charts/clickhouseServer/templates/svc-clickhouse-replica-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-clickhouseServer-replica-headless
  labels:
    app.kubernetes.io/name: clickhouseServer-replica-headless
    app.kubernetes.io/instance: release-name-replica-headless
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: "None"
  ports:
  - port: 9000
    targetPort: tcp-port
    protocol: TCP
    name: tcp-port
  - port: 8123
    targetPort: http-port
    protocol: TCP
    name: http-port
  - port: 9009
    targetPort: inter-http-port
    protocol: TCP
    name: inter-http-port
  selector:
    app.kubernetes.io/name: clickhouseServer-replica
    app.kubernetes.io/instance: release-name-replica
---
# Source: plausible-analytics/charts/clickhouseServer/templates/svc-clickhouse-replica.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-clickhouseServer-replica
  labels:
    app.kubernetes.io/name: clickhouseServer-replica
    app.kubernetes.io/instance: release-name-replica
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 9000
    targetPort: tcp-port
    protocol: TCP
    name: tcp-port
  - port: 8123
    targetPort: http-port
    protocol: TCP
    name: http-port
  - port: 9009
    targetPort: inter-http-port
    protocol: TCP
    name: inter-http-port
  selector:
    app.kubernetes.io/name: clickhouseServer-replica
    app.kubernetes.io/instance: release-name-replica
---
# Source: plausible-analytics/charts/clickhouseServer/templates/svc-clickhouse.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-clickhouseServer
  labels:
    app.kubernetes.io/name: clickhouseServer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 9000
    targetPort: tcp-port
    protocol: TCP
    name: tcp-port
  - port: 8123
    targetPort: http-port
    protocol: TCP
    name: http-port
  - port: 9009
    targetPort: inter-http-port
    protocol: TCP
    name: inter-http-port
  selector:
    app.kubernetes.io/name: clickhouseServer
    app.kubernetes.io/instance: release-name
---
# Source: plausible-analytics/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-plausible-analytics
  labels:
    helm.sh/chart: plausible-analytics-0.2.5
    app.kubernetes.io/name: plausible-analytics
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: plausible-analytics
    app.kubernetes.io/instance: release-name
---
# Source: plausible-analytics/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-plausible-analytics
  labels:
    app: plausible
    helm.sh/chart: plausible-analytics-0.2.5
    app.kubernetes.io/name: plausible-analytics
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    checksum/secret: 6b490ace7675241e78314f7794cb8d14759116216c9f9b80f3205219b75440ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible
      app.kubernetes.io/name: plausible-analytics
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app: plausible
        app.kubernetes.io/name: plausible-analytics
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-plausible-analytics
      securityContext:
        {}
      containers:
        - name: plausible-analytics
          securityContext:
            {}
          image: "plausible/analytics:v1.3.0"
          imagePullPolicy: IfNotPresent
          command:
            - /entrypoint.sh
            - run
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: release-name-plausible-analytics
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: release-name-plausible-analytics
            - name: CLICKHOUSE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: CLICKHOUSE_DATABASE_URL
                  name: release-name-plausible-analytics
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: app-tmp
              mountPath: /app/tmp
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}


      initContainers:
        - name: plausible-init
          securityContext:
            {}
          image: "plausible/analytics:v1.3.0"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -x
            - -c
            - /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: release-name-plausible-analytics
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: release-name-plausible-analytics
            - name: CLICKHOUSE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: CLICKHOUSE_DATABASE_URL
                  name: release-name-plausible-analytics
          volumeMounts:
            - name: app-tmp
              mountPath: /app/tmp
      volumes:
        - name: app-tmp
          emptyDir: {}
---
# Source: plausible-analytics/charts/clickhouseServer/templates/statefulset-clickhouse.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-clickhouseServer
  labels:
    app.kubernetes.io/name: clickhouseServer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  serviceName: release-name-clickhouseServer-headless
  selector: 
    matchLabels: 
      app.kubernetes.io/name: clickhouseServer
      app.kubernetes.io/instance: release-name
  template:
    metadata: 
      labels: 
        app.kubernetes.io/name: clickhouseServer
        app.kubernetes.io/instance: release-name
    spec:
      initContainers:
      - name: init
        image: busybox:1.31.0
        imagePullPolicy: IfNotPresent
        args:
        - /bin/sh
        - -c
        - |
          mkdir -p /etc/clickhouse-server/metrica.d
      containers:
      - name: release-name-clickhouseServer
        image: yandex/clickhouse-server:20.8
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-port
          containerPort: 8123 
        - name: tcp-port
          containerPort: 9000
        - name: inter-http-port
          containerPort: 9009
        livenessProbe: 
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: release-name-clickhouseServer-data
          mountPath: /var/lib/clickhouse
        - name: release-name-clickhouseServer-logs
          mountPath: /var/log/clickhouse-server
        - name: release-name-clickhouseServer-config
          mountPath: /etc/clickhouse-server/config.d
        - name: release-name-clickhouseServer-metrica
          mountPath: /etc/clickhouse-server/metrica.d
        - name: release-name-clickhouseServer-users
          mountPath: /etc/clickhouse-server/users.d
        securityContext:
          privileged: true
          runAsUser: 0
      volumes: 
      - name: release-name-clickhouseServer-data
        emptyDir: {}
      - name: release-name-clickhouseServer-logs
        emptyDir: {}
      - name: release-name-clickhouseServer-config
        configMap:
          name: release-name-clickhouseServer-config
          items:
          - key: config.xml
            path: config.xml
      - name: release-name-clickhouseServer-metrica
        configMap:
          name: release-name-clickhouseServer-metrica
          items:
          - key: metrica.xml
            path: metrica.xml
      - name: release-name-clickhouseServer-users
        configMap:
          name: release-name-clickhouseServer-users
          items:
          - key: users.xml
            path: users.xml
  volumeClaimTemplates:
---
# Source: plausible-analytics/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-plausible-analytics
  labels:
    helm.sh/chart: plausible-analytics-0.2.5
    app.kubernetes.io/name: plausible-analytics
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  tls:
    - secretName: release-name-plausible-analytics
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-plausible-analytics
                port:
                  number: 80
---
# Source: plausible-analytics/templates/cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: release-name-plausible-analytics
spec:
  commonName: "chart-example.local"
  secretName: release-name-plausible-analytics
  dnsNames:
    - "chart-example.local"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
# Source: plausible-analytics/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-plausible-analytics-test-connection"
  labels:
    helm.sh/chart: plausible-analytics-0.2.5
    app.kubernetes.io/name: plausible-analytics
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-plausible-analytics:80']
  restartPolicy: Never
